// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpookkgjqwhromusnsur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwb29ra2dqcXdocm9tdXNuc3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTIwNDksImV4cCI6MjA2MTY4ODA0OX0.SBrftkk59PcAS8MHfiIdse7HELLPYAJqFWt47oTk-nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);